#ifndef _SELECT_PROGRAM_H
#define _SELECT_PROGRAM_H

#define HELLO_WORLD 0
#define TEST_TEMP 1
#define TEST_SOIL 2
#define TEMP_TRANSMIT 3
#define SOIL_TRANSMIT 4
#define TEMP_SOIL_TRANSMIT 5

#define PROGRAM HELLO_WORLD
#endif
